const productos = [
{
    id: 0,
    name: "Camibuzo de dinosaurio",
    precio: 100000,
    instock: 50,
    imgsrc: "./img/superior1.png",
},
{
    id: 1,
    name: "Camibuzo de chica Kitsune",
    precio: 200000,
    instock: 80,
    imgsrc: "./img/superior2.png",
},
{
    id: 2,
    name: "Buzo de gatito",
    precio: 160000,
    instock: 30,
    imgsrc: "./img/superior3.jpg",
},
{
    id: 3,
    name: "Pantalón bota ancha",
    precio: 80000, 
    instock: 23,
    imgsrc: "./img/inferior1.jpeg",
},
{
    id: 4,
    name: "Pantalón cuadros",
    precio: 120000,
    instock: 6,
    imgsrc: "./img/inferior2.jpeg",
},
{
    id: 5,
    name: "Pantalón Jogger",
    precio: 135000,
    instock: 14,
    imgsrc: "./img/inferior3.jpg",
},
{
    id: 6,
    name: "Conjunto estilo colegiala",
    precio: 210000,
    instock: 12,
    imgsrc: "./img/conjunto1.png",
},
{
    id: 7,
    name: "Conjunto leyenda China",
    precio: 250000,
    instock:15,
    imgsrc: "./img/conjunto2.png",
},
{
    id: 8,
    name: "Conjunto Monte Fuji",
    precio: 280000,
    instock: 5,
    imgsrc: "./img/conjunto3.png",
}
]